name: oneAPI-build

on: [push, pull_request]

jobs:
  setup:
      runs-on: ubuntu-latest
      name: Install OneAPI tools
      steps:
        - uses: actions/checkout@v3
        - uses: rscohn2/setup-oneapi@v0
          with:
            list: true
            components: |
              - ccl
              - dnn
              - dpl
              - ippcp
              - tbb
              - vpl
              - mkl
        - name: Setup vars
          run: |
            source /opt/intel/oneapi/setvars.sh
        - name: Build all kernels
          run:  |
            cd dev/sycl
            # Use the Intel DPC++ compiler (icpx) and run make
            make CC=icpx 

        - name: run all kernels
          run: |
            cd dev/sycl
            make run_all CC=icpx

    
