name: oneAPI-build

on: [push, pull_request]

jobs:
  dpcpp:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Cache install
        id: cache-dpcpp
        uses: actions/cache@v2
        with:
          path: /opt/intel/oneapi
          key: oneapi-update3

      - name: Intel Apt repository
        if: steps.cache-dpcpp.outputs.cache-hit != 'true'
        run: |
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/oneAPI.list" -o APT::Get::List-Cleanup="0"

      - name: Install OneAPI
        if: steps.cache-dpcpp.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -y intel-oneapi-dpcpp-cpp-compiler intel-oneapi-mkl-devel
      - name: Setup environment
        run: |
          source /opt/intel/oneapi/setvars.sh
          printenv >> $GITHUB_ENV

      - name: Build all kernels
        run:  |
          cd dev/sycl
          # Use the Intel DPC++ compiler (icpx) and run make
          make CC=icpx 

      - name: run all kernels
        run: |
          cd dev/sycl
          make run_all CC=icpx

    
